### ISSUE TITLE
Vagrant guest plugin

### ISSUE THREAD

**Issue by maxcnunes** [rancher/os-vagrant#12]
Hi,

I have been playing around Vagrant + RancherOS yesterday and I have some problems to configure the RancherOS capabilities in my packer builder of RancherOS for vangrant.

There is an issue (#1) related to this problem that has already been closed. But the current [solution](https://github.com/rancherio/os-vagrant/issues/1#issuecomment-84611400) was kind a workaround.

I would like to solve this problem with a better approach, so I created a vagrant guest plugin for RancherOS - https://github.com/maxcnunes/rancheros-guest.

Using this plugin the capabilities configurations for RancherOS works since the first `vagrant up`.

But I think this approach could be even better if this plugin was embedded on vagrant guest plugins ([available guests](https://github.com/mitchellh/vagrant/tree/master/plugins/guests)), so I would like to create a pull request for Vagrant including this new guest plugin into Vagrant project.

Since this project seems like the official project for Vagrant + RancherOS. Before I send the pull request for Vagrant I would like to know from you guys if there is any problem I include RancherOS guest on Vagrant project? Is there any reasons why you guys have not done it yet?

Cheers,

**Comment by ailispaw** [comment]
@maxcnunes Thank you for the plugin. I like your solution and thank you for choosing my code.

But my code is not good for the original Vagrant, because `change_host_name` dose just change the system containers but base os underneath them. So once restarting the container, it will gone.
I believe `change_host_name` has to change hostname on the base os instead and dose like `configure_networks` with `rancherctl` somehow.
And also because RancherOS seems still in progress, you had better wait for the stable release.

Anyway I will use your plugin for now. Thanks again. :)

**Comment by cloudnautique** [comment]
@maxcnunes Thanks for putting this together, and taking the time to discuss with us. We agree that the solution as it is today is sub-optimal and that the ultimate solution is to get a real OS plugin in mainline Vagrant. In order to get an image in a usable state to users quickly we took this path. 

We felt the underlying os APIs for performing these actions needed to be more stable. We have been adding these things to RancherOS over the past couple releases. We needed the network configuration, which todays box leverages, a reliable way to determine the os (we added lsb-release), and setting hostname. There is a pull request in Rancher OS for setting the host name officially. Since things have been changing a lot under the hood, and we wanted to make sure we could make changes quickly without impacting other projects we went this way.

Once the host name gets into the base, all the pieces will be there to put together an official Vagrant plugin. As things bake, it might make sense to use the  `vagrant plugin install <plugin>` method. AFAIK it only requires a ruby gem. We would like to be the official owners of the plugin, as people will come to us for support issues and questions. I can create the repository and we can start working from there. Sound reasonable?

Also, if you are interested, we use Packer to do our builds also. The repository is [cloudnautique/rancher-packer](https://github.com/cloudnautique/rancher-packer) it will be moving over to Rancherio once its cleaned up a little bit. Open an issue or chat with us on #rancher on freenode if something doesn't make sense. We want to make this stuff better.

**Comment by maxcnunes** [comment]
I'm glad I got these feedbacks from you guys before sending a pull request to Vagrant. I didn't know about those limitations on RancherOS. Makes sense wait for this new feature to change the host name before adding RancherOS as a guest plugin on Vagrant.

@cloudnautique I agree this temporary plugin should belongs to Rancher group. Actually that is one of the reasons I came here before even publishing the plugin on ruby gems. I could transfer the project to rancherio (I don't know if I need any permission for that) or if you prefer create another project that is ok. Just would be awesome have this plugin available on ruby gem to make the configuration easier while is not added the guest plugin on Vagrant.

@cloudnautique I saw your packer project, which looks pretty good. But I need a vm more specific for my daily development tasks. For instance I need [nginx-proxy](https://github.com/jwilder/nginx-proxy), docker-compose and built in configurations for Vagrant file. Something similar that I have been using with CoreOS https://github.com/dockito/devbox-packer.

**Comment by trompx** [comment]
Hi,

I wanted to install docker-compose but could not copy the binary because of this problem. I get the following message :
"No installation found.
The guest's platform is currently not supported, will try generic Linux method...
Copy iso file C:\Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
stdin: is not a tty
mount: Could not find any loop device. Maybe this kernel does not know
       about the loop device? (If so, recompile or `modprobe loop'.)"

Hopefully, Vagrant will add rancherOS to his list of available guest soon...

**Comment by cloudnautique** [comment]
@trompx , you would have to do a `scp` or `rsync` over ssh into the host to copy the binary.

**Comment by ashmckenzie** [comment]
@trompx I added the following to the `Vagrantfile` and had success:

```
Vagrant.configure(2) do |config|
  config.vbguest.auto_update = false
  --snip--
```

**Comment by deniseschannon** [comment]
We're no longer supporting our vagrant repo and have moved to supporting docker-machine to start up RancherOS. As a result, we will be closing the issues tab in the repo.

[Learn how easy it is to use RancherOS with docker-machine](http://docs.rancher.com/os/running-rancheros/workstation/docker-machine/).
